name: "Build Systems"
on:
  pull_request:
  push:
jobs:
  hermione:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#darwinConfigurations.hermione-x86.system
#     - run: ./result/sw/bin/${{ env.system }}-rebuild build --flake .#${{ env.name }}

  gilderoy:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#nixosConfigurations.gilderoy.config.system
#     - run: ./result/sw/bin/${{ env.system }}-rebuild build --flake .#${{ env.name }}
