name: "Build Systems"
on:
  pull_request:
  push:
jobs:
  hermione:
    runs-on: macos-latest
    env:
      name: hermione-x86
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: "nix build .#darwinConfigurations.${ env.name }.system"
    - run: ./result/sw/bin/darwin-rebuild build --flake ".#${ env.name }"

  gilderoy:
    runs-on: ubuntu-latest 
    env:
      name: gilderoy
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: "nix build .#darwinConfigurations.${ env.name }.system"
    - run: ./result/sw/bin/darwin-rebuild build --flake ".#${ env.name }"
