name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#darwinConfigurations.hermione-x86.system
    - run: ./result/sw/bin/darwin-rebuild switch --flake '.#hermione-x86'
